name: GH-Actions build/test

on:
  push:
    branches: [ devel/gh-actions ]

env:
  SETUP_PATH: .:.ci
  SET: test01
  VV: 1
  BASE_RECURSIVE: NO
  CMP: gcc
  APT: re2c
  CHOCO: re2c
  BREW: re2c

jobs:
  build:
    name: Build ${{ matrix.cmp }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CMP: ${{ matrix.cmp }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, windows-2019, windows-2016, macos-10.15]
        cmp: [gcc]
        include:
          - cmp: vs2019
            os: windows-2019
          - cmp: vs2017
            os: windows-2016

    steps:
    - uses: actions/checkout@v2
    - name: Prepare and compile dependencies
      run: python cue.py prepare
    - name: Build main module (example app)
      run: python cue.py build
    - name: Run main module tests
      run: python cue.py test
    - name: Collect and show test results
      run: python cue.py test-results

  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, windows-2019, windows-2016, macos-10.15]

    steps:
    - uses: actions/checkout@v2
    - name: Show initial environment
      run: python cue-test.py env
    - name: Run unit tests
      run: python cue-test.py
