name: ci-scripts CI build/test

on:
  push:
    branches: [ devel/gh-actions ]

env:
  SETUP_PATH: .:.ci
  SET: test01
  VV: 1
  BASE_RECURSIVE: NO
  CMP: gcc
  APT: re2c

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: python cue.py prepare
    - name: build
      run: python cue.py build
    - name: test
      run: python cue.py test
    - name: test-results
      run: python cue.py test-results

  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-16.04, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: show environment
      run: python cue-test.py env
    - name: unit tests
      run: python cue-test.py
